### ISSUE TITLE
..error applying theme on NP++ v6.9.2...

### ISSUE THREAD

**Issue by malJohann** [Nidre/VS2015-Dark-Npp#10]
Hi,

I get the following error applying the theme on NP++ v6.9.2: Load stylers.xml failed!

I'm on Windows7sp1 32bit skinned to look like Windows10.

Please help if at all possible.

Cheers,
Johann

![image](https://cloud.githubusercontent.com/assets/22045381/18301635/5d22da8c-7516-11e6-9e4d-14632b2fe79a.png)

**Comment by Ludomancer** [comment]
Duplicate.
See: https://github.com/Nidre/VS2015-Dark-Npp/issues/8
