### ISSUE TITLE
Different font for TAG style in CSS lexer.

### ISSUE THREAD

**Issue by santsukevich** [Nidre/VS2015-Dark-Npp#12]
I'm not sure if it's wrong or not.
**VS2015-Dark.xml** line **276**: 
`<WordsStyle name="TAG" styleID="1" fgColor="569CD6" bgColor="1E1E1E" fontName="Batang" fontStyle="0" fontSize="" />`
![css](https://cloud.githubusercontent.com/assets/8876120/18548996/65164532-7b54-11e6-9ec7-f25bff82248c.png)

**Comment by jessiewestlake** [comment]
Most helpful GitHub issue I've ever seen, lol
