### ISSUE TITLE
Load stylers.xml failed!

### ISSUE THREAD

**Issue by jlchavis0844** [Nidre/VS2015-Dark-Npp#14]
Yeah, that error message.

**Comment by rfresow** [comment]
Please be specific. When do you get this error? What version of npp are you using?

**Comment by jlchavis0844** [comment]
Sorry for the short report. Originally, Notepad++ V6.8.8 32-bit and it occurred when trying to load the style in settings->Style Config. Just tried it on 6.9.2 32 bit and 64bit (new installs). Same problem. I get the Load stylers.xml failed! if I cancel out it's ok. If I use Save and close, it crashes.
![image](https://cloud.githubusercontent.com/assets/14359017/18738108/6a639294-804d-11e6-9f98-b2865b7fb358.png)

**Comment by rfresow** [comment]
Probably the VS2015-Dark.xml got corrupt. Npp can't parse it. Try open the `%APPDATA%\Notepad++\themes\VS2015-Dark.xml` and verify that it is clean xml. Compare it with [https://github.com/Nidre/VS2015-Dark-Npp/blob/master/VS2015-Dark.xml](url)

**Comment by jlchavis0844** [comment]
Something happened with the file because the one I had was 2000+ lines while the one linked above was only ~705. Regardless, it's working great now. Thanks.

**Comment by Ludomancer** [comment]
@jlchavis0844 @rfresow 

I'm guessing this was due to a corrupted file. Closing this, feel free to re-open if needed.
