### ISSUE TITLE
Syntax highlighting issue for NVARCHAR keyword [SQL]

### ISSUE THREAD

**Issue by dehghani-mehdi** [Nidre/VS2015-Dark-Npp#16]
Hi,

I'm using latest version of your theme & NPP.
For SQL language, `NVARCHAR` keyword shown white, instead of blue.
For all other keywords/types your theme works perfectly.

BTW, Great theme!

__Update__
`UNIQUEIDENTIFIER` also has the same problem.

Thank you !

**Comment by Ludomancer** [comment]
@dehghani-mehdi 

Can you send me an example code with UNIQUEIDENTIFIER?

I've fixed nvarchar issue with Commit  d3047c5a0e1f3ecfa203526eb80465f1ea8f6828

**Comment by dehghani-mehdi** [comment]
Here you go:

```
DECLARE @id UNIQUEIDENTIFIER;

-- OR

CREATE TABLE Sample (
    Id INT NOT NULL;
    Code UNIQUEIDENTIFIER NOT NULL;
);
```

**Comment by Ludomancer** [comment]
@dehghani-mehdi 

Latest commit should fix that, can you test with it.

**Comment by dehghani-mehdi** [comment]
I just tested & seems like everything works perfectly now.

Thank you !
