### ISSUE TITLE
Theme fails to load when using Notepad++ through Wine on Ubuntu 16.10

### ISSUE THREAD

**Issue by ThreePinkApples** [Nidre/VS2015-Dark-Npp#17]
Was looking for a good theme for my Notepad++ and found this, but it fails to load on my setup. 
The message I get is "Load stylers.xml failed!" when I click on VS2015-Dark

**Comment by ghost** [comment]
Update: I realized it was because we need to click on the file (and not right-click > save as) to get to the actual contents, then click "Raw", and finally select all the content and paste it into the XML file itself.

I'm using Notepad++ on Windows 10, and I also had this very same error message.

**Comment by Ludomancer** [comment]
Closing this one since a solution was provided and the issue is not related to the project itself.
