### ISSUE TITLE
[Suggestion] Current line background

### ISSUE THREAD

**Issue by JayJayJazz** [Nidre/VS2015-Dark-Npp#18]
Hi,

this is just a suggestion. I like to have the current line to be more visible. So I changed a setting in your theme:

Current line background --> Background colour:
default value for all three colours is "30". I changed it to "50" for all three colours, so that the line is barely visible.

What do you think?

**Comment by Ludomancer** [comment]
@JayJayJazz 

You were right, I've compared with Visual Studio 2015 and colors were off. I've updated the theme, enjoy :)
