### ISSUE TITLE
Load stylers.xml failed

### ISSUE THREAD

**Issue by dinazil** [Nidre/VS2015-Dark-Npp#24]
I put the theme in the themes folder but when I try selecting it I get the following error:
![image](https://cloud.githubusercontent.com/assets/5171005/21213279/eb37e84e-c29b-11e6-8f6e-38154b73a5b8.png)

And after I click OK notepad++ crashes.

Notepad++ version: 7.2.2 32-bit
OS: Microsoft Windows 10 Enterprise, Version 10.0.10240

**Comment by dinazil** [comment]
Duplicate

**Comment by dinazil** [comment]
OK, I feel a little silly now, first because it's a duplicate and second because the problem was really silly. You should update your instructions though. Right-clicking the file and saving doesn't really work.

**Comment by Ludomancer** [comment]
@dinazil If you right click the link that I've provided in the description it works actually.
If you scroll would up and right click on the file up there it doesn't :)

I've also updated the description, thanks for the suggestion :) Hopefully it should be less error prone now :)

**Comment by dinazil** [comment]
Yes, now I feel really stupid. But the change to "here" should definitely take care of this for good. Thanks!
