### ISSUE TITLE
notepad 6.8.6 crashes when changing the theme to VS2015-Dark

### ISSUE THREAD

**Issue by antonkukoba** [Nidre/VS2015-Dark-Npp#26]

**Comment by Ludomancer** [comment]
That's a pretty old version of Notepad++ current is 7.x. I will take a look at it when I can.

**Comment by rollsch** [comment]
I'm using notepad++ 7.2.2 and it also crashes with no error message using this theme. Anything I can do to help? Any commands I can pass so it logs why it crashes for you?

**Comment by rollsch** [comment]
Ok found out the issue. If you save the XML file after viewing it in a browser, it saves it as HTML, not the raw XML file.

If you download the file correctly, this issue does not occur. I would put something on the main page to indicate this to people.

**Comment by Ludomancer** [comment]
@rolandh Thanks for the advice, glad the issue has been solved.
