### ISSUE TITLE
Error: load stylers.xml failed

### ISSUE THREAD

**Issue by omarzd** [Nidre/VS2015-Dark-Npp#27]
Hello. I followed the instructions. I'm using NP++ v7.3 32bit. When I select the theme from the drop down menu in style configurator, I get a dialog box saying "load stylers.xml failed".

**Comment by Ludomancer** [comment]
Please search before posting an issue.

**Comment by omarzd** [comment]
lol omg it's duplicated like ten times.. sorry about that.
