### ISSUE TITLE
Tools bar is white

### ISSUE THREAD

**Issue by zhuchun** [Nidre/VS2015-Dark-Npp#3]
Hi, this theme is great, thanks!
Is that possible to make tools bar and tabs dark?

![nppp_white](https://cloud.githubusercontent.com/assets/3390745/13195902/1a785dde-d7f9-11e5-8b30-fdf4b2c884fe.png)

**Comment by Ludomancer** [comment]
As far as I know, this is not possible with themes. But if you feel adventurous,  here I've found an old articles explaining how you can grab the source code, change the colors of Notepad++ and build it :)

**Comment by omarzd** [comment]
The title, menu and tool bars are all governed by the windows theme and thus can be changed using a dark windows theme. I've done just that, however, my tab bar is still in the original bright color.
