### ISSUE TITLE
Thanks! A wish (Feature request) / Suggestion!

### ISSUE THREAD

**Issue by spurgeonbj** [Nidre/VS2015-Dark-Npp#4]
Hi!

Thanks a ton for the nice plugin / theme.

If possible, kindly consider extending the dark theme to menu bar/ tool bars too. 

As of now, only the document code area is dark.

Warm regars and gratitude!

**Comment by mokeev1995** [comment]
yeah, that would be great!

**Comment by spurgeonbj** [comment]
Thank you! God bless you! :-)

**Comment by TyraelElDruin** [comment]
Just wanted to say thank you for posting this :) :+1:

**Comment by Ludomancer** [comment]
Unfortunately, Notepad++ does not support such customization. If anyone has any way to make that work, I would be happy consider this, since I also would like to have it dark :)
