### ISSUE TITLE
Crashes with Notepad++ 6.9

### ISSUE THREAD

**Issue by nashmuhandes** [Nidre/VS2015-Dark-Npp#7]
The theme crashes when I try to load it. Here's my Notepad++ debug info:

Notepad++ v6.9
Build time : Feb 21 2016 - 21:27:55
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1
Plugins : ComparePlugin.dll NppAutoIndent.dll NppExec.dll PluginManager.dll 

Note: It doesn't matter if I ran NP++ as Admin Mode or not, it still crashes.

**Comment by BenedekFarkas** [comment]
Confirmed with v6.9 and v6.9.1:

```
Notepad++ v6.9.1
Build time : Mar 28 2016 - 19:48:40
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 8.1
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 
```

**Comment by nashmuhandes** [comment]
Does not crash if I actually download the entire repo as a ZIP file to my hard disk, and then manually extract the XML out. It only crashes when viewing in Raw mode and saving as from the browser. Going to assume Raw display screws up the formatting. I'm going to close this

**Comment by BenedekFarkas** [comment]
Indeed, thanks!
