### ISSUE TITLE
Error loading stylers.xml

### ISSUE THREAD

**Issue by nandakishore8031** [Nidre/VS2015-Dark-Npp#8]
When I'm trying to load I got an error saying "Load stylers.xml Failed!"
Can you let me know the issue please.

**Comment by Ludomancer** [comment]
@nandakishore8031 

Can you tell me what are exact steps you are taking?

I've just tested this with the latest version of Notepad++ and the theme, and didn't see any issues. Details would be helpful.

**Comment by nandakishore8031** [comment]
Hi,

I followed below steps:
1. Added VS2015-Dark.xml in themes folder of notepad++.
2. Selected VS2015-Dark from Settings -> Style Configurator -> VS2015-Dark
3. Then got error.

Thanks,
Nandakishore A,
MMIS,
435 374 6189
My LinkedIn http://www.linkedin.com/in/nandakishorea/

**Comment by hakimkhalafi** [comment]
@nandakishore8031 

That's probably because you right clicked the XML from the front page and saved from there. This includes the entire GitHub HTML page. 

The actual raw .xml file that you want to right click and save-as is this one

https://raw.githubusercontent.com/Nidre/VS2015-Dark-Npp/master/VS2015-Dark.xml

**Comment by Ludomancer** [comment]
@nandakishore8031 

Can you try what @hakimkhalafi suggested and let me know if it solves your problem? 

Just to make thing easier to double check that the file you've downloaded have **"<?xml version="1.0" encoding="Windows-1252" ?>"** at the beginning of it when you open it with any text editor. If you don't see that, you've definitely downloaded the incorrect file.

**Comment by nandakishore8031** [comment]
Thanks Guys.
This is working now.
When saved, it saved with HTML content so it couldn't load.

Now its working. Thanks for your suggestions.

Thanks,
Nandakishore A,
MMIS,
435 374 6189
My LinkedIn http://www.linkedin.com/in/nandakishorea/
