### ISSUE TITLE
Update install instructions for per-user settings

### ISSUE THREAD

**Issue by aureq** [Nidre/VS2015-Dark-Npp#9]
Cool theme, but the install instructions aren't suitable for non admin users. Here is how it works for these users:
1. Go to `%APPDATA%\Notepad++`
2. Create a folder `themes`
3. Place the `.xml`
4. Restart Notepad++.
5. Open _Settings->Style Configurator_.
6. Select `VS2015-Dark` from the theme drop-down box.
7. Click _Save & Close_

**Comment by Ludomancer** [comment]
Done :) Thanks for the suggestion ;)
